import pytest
from app import clean_markdown_for_streamlit
from src.agent.graph import extract_text_from_response

def test_clean_markdown_for_streamlit():
    # 1. Escape standalone dollar signs
    assert clean_markdown_for_streamlit("$94,827") == "\\$94,827"
    
    # 2. Clean broken LaTeX fractions generated by the Math Agent
    assert clean_markdown_for_streamlit(r"\frac{\94,827 - $97,690}{$97,690}") == r"(94,827 - \$97,690 / \$97,690)"
    
    # 3. Fix stray backslashes before numbers
    assert clean_markdown_for_streamlit(r"\4,355") == "4,355"
    
    # 4. Handle empty input gracefully
    assert clean_markdown_for_streamlit("") == ""

def test_extract_text_from_response():
    # 1. Standard string extraction
    assert extract_text_from_response("MSFT") == "MSFT"
    
    # 2. Google SDK List of Dicts extraction
    mock_sdk_response = [{'TYPE': 'TEXT', 'text': 'MSFT', 'EXTRAS': {'SIGNATURE': 'xyz'}}]
    assert extract_text_from_response(mock_sdk_response) == "MSFT"
    
    # 3. List of strings
    assert extract_text_from_response(["Apple ", "Inc."]) == "Apple Inc."